#!/bin/sh

xterm -si -sb -sl 1000 -e './launch_stage' &

sleep 5

for robot in robot_0 robot_1 robot_2;
do
	echo "Launching ./launch_${robot}"
	xterm -si -sb -sl 1000 -e "./launch_${robot}" &
	sleep 8
done

xterm -si -sb -sl 1000 -e 'rosbag record /experiment /tasks/announce /tasks/bid /tasks/award /tasks/status' &

xterm -si -sb -sl 1000 -e './launch_auctioneer' &
