#!/bin/sh

ROS_PORT=11313
export ROS_HOSTNAME=`/bin/hostname`
export ROS_MASTER_URI=http://${ROS_HOSTNAME}:${ROS_PORT}/

#### move_base
xterm -e 'roslaunch multirobot_stage robot_1_move_base.launch' &
sleep 10

#### robot_controller
xterm -e 'rosrun robot_controller robot_controller.py robot_1 3.0 1.0' &

# Do nothing. This lets us catch and forward SIGINT to child processes
# launched above.
while [ 1 ]
do
 sleep 1
done
