#!/bin/sh

ROS_PORT=11311
export ROS_HOSTNAME=`/bin/hostname`
export ROS_MASTER_URI=http://${ROS_HOSTNAME}:${ROS_PORT}/

#### move_base
xterm -si -sb -sl 1000 -e 'roslaunch auctioneer auctioneer.launch' &
sleep 5

# Do nothing. This lets us catch and forward SIGINT to child processes
# launched above.
while [ 1 ]
do
 sleep 1
done
